package com.myspace.mortgage_app;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApprovalMsg implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Application")
	private com.myspace.mortgage_app.Application application;
	@org.kie.api.definition.type.Label("BPMProcessID")
	private Long BPMProcessID;

	public ApprovalMsg() {
	}

	public com.myspace.mortgage_app.Application getApplication() {
		return this.application;
	}

	public void setApplication(com.myspace.mortgage_app.Application application) {
		this.application = application;
	}

	public java.lang.Long getBPMProcessID() {
		return this.BPMProcessID;
	}

	public void setBPMProcessID(java.lang.Long BPMProcessID) {
		this.BPMProcessID = BPMProcessID;
	}

	public ApprovalMsg(com.myspace.mortgage_app.Application application,
			java.lang.Long BPMProcessID) {
		this.application = application;
		this.BPMProcessID = BPMProcessID;
	}

}